import Head from "next/head";
import Image from "next/image";
import Sidebar from "../../components/chat/Sidebar";
import Navbar from "../../components/Navbar";
export default function Home() {
  return (
    <div>
      <Head>
        <title>Chat devmates</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Sidebar />
    </div>
  );
}
